replicaCount: 3

image:
  repository: "ghcr.io/dfradehubs/lokalise-proxy-authenticator"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

env:
  - name: LISTEN_PORT
    value: "8080"
  - name: LOGIN_POST_PATH
    value: "/login/signin"
  - name: LOKALISE_API_URL
    value: "https://api.lokalise.com"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 5

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  timeoutSeconds: 5

nodeSelector: {}

affinity: {}

tolerations: []

serviceAccount:
  create: false

podSecurityContext: {}